[TEXT-229] Add XmlEncoderStringLookup/XmlDecoderStringLookup
apache/commons-text pull request #449
Opened 2023-08-15 13:17 UTC by michael-o

This closes #449

2023-08-20 15:15 UTC, garydgregory commented
Since this PR relies on `StringEscapeUtils.escapeXml10(key)` and XML 1.1 exists, shouldn't we either support both or change the names in this PR to explicitly call out XML 1.0? For example, `DefaultStringLookup.XML_DECODER` -> `DefaultStringLookup.XML_DECODER_1_0`.

2023-08-20 16:16 UTC, michael-o commented
I'd say that 1.0 should be the default since 1.1 gained little traction. If someone wants later 1.1 support we can add, but given that no one even requested 1.0 for the past years I am reluctant to rename those coders.

2023-08-20 17:05 UTC, elharo requested changes

2023-08-20 17:05 UTC, elharo commented on src/test/java/org/apache/commons/text/lookup/XmlEncoderStringLookupTest.java
> +    private static final String DATA = "&lt;element&gt;";
inline. DATA is much less clear than the literal string. Named constants are for numbers, not strings.

2023-08-20 17:05 UTC, elharo commented on src/test/java/org/apache/commons/text/lookup/XmlDecoderStringLookupTest.java
> +    private static final String DATA = "<element>";
inline. DATA is much less clear than the literal string. Named constants are for numbers, not strings.

2023-08-20 17:05 UTC, elharo commented on src/main/java/org/apache/commons/text/lookup/XmlEncoderStringLookup.java
> +    XmlEncoderStringLookup() {
private

2023-08-20 17:05 UTC, elharo commented on src/main/java/org/apache/commons/text/lookup/XmlDecoderStringLookup.java
> +    XmlDecoderStringLookup() {
private

2023-08-20 18:35 UTC, michael-o commented
@elharo, I have copied a pre-existing class which uses the same pattern as other classes. I won't change a single class, this needs to be done for all of them in a separate PR.

2023-08-20 22:05 UTC, elharo commented
I cry [Emerson](https://www.goodreads.com/quotes/353571-a-foolish-consistency-is-the-hobgoblin-of-little-minds-adored). Consistency with bad code is not a virtue. I see no reason to make the new API excessively complex, public, and hard-to-read.

2023-08-23 13:09 UTC, garydgregory commented
> @elharo, I have copied a pre-existing class which uses the same pattern as other classes. I won't change a single class, this needs to be done for all of them in a separate PR.

Some constructors are private, some are not, you just happen to have picked a class for your template that had its constructor package-private instead to private.

2023-08-23 13:32 UTC, merged

2023-08-23 13:36 UTC, garydgregory commented
https://issues.apache.org/jira/projects/TEXT/issues/TEXT-229